# Generated by Django 4.1.1 on 2022-09-23 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RacingVenue',
            new_name='RacingEvent',
        ),
        migrations.RenameField(
            model_name='racingevent',
            old_name='racetype',
            new_name='racingevent',
        ),
    ]
