# Generated by Django 4.1.1 on 2022-10-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal1', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='racingevent',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
    ]
